---
- hosts: redhat
  become: yes
  tasks:
  - name: copy file from src des
    copy:
      src: /home/ansible/myinv
      dest: /home/ansible/myinventry
  - name: get the url
    get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /home/ansible/jenkins.war

